image: laravelsail/php81-composer

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - composer install
    - composer lint
    - composer larastan
  allow_failure: true

pest:
  stage: test
  script:
    - cp .env.example .env
    - composer install
    - php artisan key:generate
    - composer test -- --do-not-cache-result --log-junit pest-report.xml
  artifacts:
    when: always
    reports:
      junit: pest-report.xml

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - mkdir -p ~/.ssh
    - eval $(ssh-agent -s)
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - ssh-add <(echo "$SSH_PRIVATE_KEY" | tr -d '\r')
  script:
    - composer install
    - composer envoy run deploy
  environment:
    name: production
    url: https://fpl.kuprov.ru
  only:
    - main
